# Generated by Django 3.2.4 on 2021-10-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Get_and_insert_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='db',
            name='Address',
            field=models.TextField(null=True),
        ),
    ]
